[project]
name = "dnn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "opencv-python>=4.13.0.90",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
]
